Spring 7 hw 41
YuraBondarenko/Cinema pull request #10
Opened 2021-02-16 17:30 UTC by YuraBondarenko

2021-02-16 18:21 UTC, Max-Pochepets approved these changes

2021-02-16 18:21 UTC, Max-Pochepets commented on src/main/java/com/dev/cinema/controller/UserController.java
> +    public UserResponseDto get(@RequestParam @NotNull @Size(min = 4) @Valid String email) {
As I know, `@NotNull` is redundant here, cause `@RequestParam` without `required` will throw exception if you send null as parameter. @Size is OK

2021-02-16 18:21 UTC, Max-Pochepets commented on src/main/java/com/dev/cinema/model/dto/request/CinemaHallRequestDto.java
> +    @NotEmpty
[javadoc](https://javaee.github.io/javaee-spec/javadocs/javax/validation/constraints/NotEmpty.html)

2021-02-18 08:39 UTC, KseniiaMakarova requested changes

2021-02-18 08:39 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/controller/UserController.java
> +    public UserResponseDto get(@RequestParam @Size(min = 11) @Valid String email) {
does it work without the steps listed in this article?
https://www.baeldung.com/spring-validate-requestparam-pathvariable

2021-02-18 08:39 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/dto/request/CinemaHallRequestDto.java
> +    @NotEmpty
is int supported by this annotation?

2021-02-18 08:39 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/dto/request/MovieSessionRequestDto.java
> +    @Min(1)
same - this annotation does not support wrappers

2021-02-18 08:39 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/dto/request/MovieSessionRequestDto.java
> +    @Min(1)
same

2021-02-18 08:39 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/lib/PasswordValidatorAnnotation.java
> +    }
do you need this?

2021-02-18 10:01 UTC, KseniiaMakarova approved these changes

2021-02-18 10:02 UTC, merged