Hibernate 5 hw31
YuraBondarenko/Cinema pull request #4
Opened 2021-02-02 08:50 UTC by YuraBondarenko

2021-02-02 16:26 UTC, Baldinini approved these changes

2021-02-02 16:56 UTC, KseniiaMakarova requested changes

2021-02-02 16:56 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/Main.java
> +        user.setPassword("pass");
there is no need to set these values to user before registration

2021-02-02 16:56 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/Main.java
> +        authenticationService.register(user.getEmail(), user.getPassword());
```suggestion
        User user = authenticationService.register("email", "pass");
```

2021-02-02 16:56 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/security/PasswordHashing.java
> +public class PasswordHashing {
```suggestion
public class HashUtil {
```

2021-02-03 07:26 UTC, KseniiaMakarova approved these changes

2021-02-03 07:48 UTC, merged